<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>อายุคำนวณอัตโนมัติเมื่อกรอกวันเกิด</description>
   <name>auto_age</name>
   <tag></tag>
   <elementGuidId>624aeee5-b27a-4ebd-a024-f8caa59783ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;age&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
